# CMI
sourceId: 99
cmiTitle: "Teachings of Christ Mind"

# Setup
title:        'The Library'
tagline:      ''
description:  ''
url:          'https://www.christmind.info'
baseurl:      ''
keywords:     "Christ Mind, cmi, jesus, raj, acim"
src-url:      'https://www.christmind.info'
port:         9999

# About/contact
author:
  name:              Rick Mercer
  url:               https://twitter.com/rmercer33
  email:             rmercer33@gmail.com

fb-appId:     448658485318107

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections for transcripts
collections:
  acq:
    output: true
    title: "Get Acquainted"

defaults:
  - scope:
      path: ""
      type: acq
    values:
      layout: transcript
      book: "Get Acquainted"
      image: "/public/img/cmi/acq-big.jpg"
      image-width: 612
      image-height: 792
      bid: "acq"

# force inclusion of
include: [_redirects, LICENSE.txt]

exclude: [
  Gemfile, Gemfile.lock, package.json, package-lock.json, node_modules, webpack.config.js, src, project
]

